#!/usr/bin/env python3
"""Emit C test vectors so the firmware core is proven byte-exact against the
Python reference (cross-implementation proof, both directions)."""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from nacl.signing import SigningKey

from xkp.frames import Frame, FrameType, pack
from xkp.proofs import Receipt, node_id_from_verify_key, receipt_to_wire

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                   "..", "firmware", "xkoin-gateway", "test", "host", "vectors.h")


def carr(name, data):
    body = ",".join(str(b) for b in data)
    return f"static const unsigned char {name}[{len(data)}] = {{{body}}};\n"


sk = SigningKey(b"\x42" * 32)
vk = bytes(sk.verify_key)
cid = node_id_from_verify_key(vk)

frame = Frame(FrameType.RECEIPT, b"SRCNODE1", b"DSTNODE1", 305419896,
              b"hello xkoin", flags=1, ttl=6)
frame_bytes = pack(frame)

receipt = Receipt(cid, b"GATEWAY1", b"S" * 16, 123_456_789_012, 77)
wire = receipt_to_wire(receipt, sk)

with open(OUT, "w") as fh:
    fh.write("// AUTO-GENERATED by protocol/gen_vectors.py. Do not edit.\n")
    fh.write(carr("V_FRAME", frame_bytes))
    fh.write(carr("V_CLIENT_VK", vk))
    fh.write(carr("V_CLIENT_ID", cid))
    fh.write(carr("V_RECEIPT_WIRE", wire))
    fh.write("static const unsigned long long V_RECEIPT_CUMULATIVE = 123456789012ULL;\n")
    fh.write("static const unsigned int V_RECEIPT_SEQ = 77;\n")
    fh.write("static const unsigned int V_FRAME_SEQ = 305419896;\n")
print(f"wrote {os.path.normpath(OUT)} ({len(frame_bytes)}B frame, {len(wire)}B receipt)")
